apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: kube-public
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:bullseye
      

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: kube-public
spec:
  selector:
    run: httpd
  ports:
  - protocol: TCP
    port: 9998
    targetPort: 80
