apiVersion: v1
kind: Service
metadata:
  name: test-k8s-2
spec:
  selector:
    app: test-k8s-2
  # 默认 ClusterIP 集群内可访问，NodePort 节点可访问，LoadBalancer 负载均衡模式（需要负载均衡器才可用，有点少用，用Ingress代替）
  type: NodePort
  ports:
    - port: 8091        # 本 Service 的端口
      targetPort: 8080  # 容器端口
      nodePort: 31001   # 节点端口，范围固定 30000 ~ 32767

