# mkdir -p /data/k8s/test/hostpath
# echo 'Hello from Kubernetes hostpath storage' > /data/k8s/test/hostpath/index.html

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/test/hostpath"