apiVersion: v1
kind: Pod
metadata:
  name: pod-try-secret-as-volume
spec:
  containers:
  - name: try-secret-as-volume
    image: busybox:stable
    args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 300
    volumeMounts:
    - name: secret-foo
      mountPath: "/etc/foo"
      readOnly: true

  volumes:
  - name: secret-foo
    secret:
      secretName: mysecret
      # secret以volume的方式mount到pod的话，secret更新了，pod对应secret文件数据过一段时间也会动态更新
      items:  
      - key: username
        path: group1/username
      - key: password
        path: group1/password