apiVersion: v1
kind: Pod
metadata:
  name: pod-try-secret-as-envar
spec:
  containers:
  - name: try-secret-as-envar
    image: busybox:stable
    args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 300
    # 实践发现，secret更新了之后，pod里面的环境变量过一段时间也会更新
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password