apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: try-secret-as-volume
    image: busybox:stable
    args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 300
    volumeMounts:
    - name: secret-foo
      mountPath: "/etc/foo"
      readOnly: true

  volumes:
  - name: secret-foo
    secret:
      secretName: mysecret