apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: kube-public
spec:
  replicas: 3
  selector:
    matchLabels:
      run: httpd
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:bullseye
      

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: kube-public
spec:
  type: NodePort
  selector:
    run: httpd
  ports:
  - protocol: TCP
    # 底层都是iptables，去实现负载均衡 nodePort -> port -> targetPort
    nodePort: 30000   # node监听的端口
    port: 9998  # ClusterIP监听的端口
    targetPort: 80  # Pod监听的端口
    
