apiVersion: v1
kind: Pod
metadata:
  name: downward-api-volume-pod
  namespace: kube-system
  labels:
    k8s-app: downward-api-volume-pod
    node-env: test
  annotations:
    own: janetat
    build: test
spec:
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels
      - path: annotations
        fieldRef:
          fieldPath: metadata.annotations
  containers:
  - name: downward-api-volume-pod
    image: busybox
    args: 
    - sleep 
    - "3600"
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo